name: Keep Streamlit Alive

on:
  schedule:
    - cron: '*/45 * * * *'  # every 45 minutes
  workflow_dispatch:       # manual trigger option

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run the script
        run: python keep_alive.py
